### PR TITLE
Bump slackclient

### PR DESCRIPTION
**Pull request by balajijegan**
Upgrade slackclient to latest released version

@arcticfoxnv  Can you please take a look at this one?

### CODE REVIEW

**Comment by balajijegan** [comment]
thanks @arcticfoxnv  Can you give me permissions on the repo to tag and create a release?

**Comment by arcticfoxnv** [comment]
I added you and @ruthgrace as collaborators quite some time ago.  They are still waiting for your response.

**Comment by balajijegan** [comment]
Wow, missed it. Just accepted the invite. All is well now. Thanks Nick

**Comment by arcticfoxnv** [comment]
Done.

**Pull request merged**
