### PR TITLE
Add ability to send threaded responses

### PR DESCRIPTION
**Pull request by balajijegan**
Update signature for rtm_send_message. This enabled the ability to send
threaded responses.

See https://slack.dev/python-slackclient/real_time_messaging.html#sending-messages-via-the-rtm-api

### CODE REVIEW

**Comment by amckenna-pinterest** [comment]
Or even:
```
    def send_message(self, channel, text, **kwargs):
        """
        Sends a message to the specified channel
        * channel - The channel to send to.  This can be a SlackChannel object, a channel id, or a channel name
        (without the #)
        * text - String to send
        """
        # This doesn't want the # in the channel name
        if isinstance(channel, SlackRoomIMBase):
            channel = channel.id
        self.log.debug("Trying to send to %s: %s", channel, text)
        self.sc.rtm_send_message(channel, text)
        self.sc.rtm_send_message(channel, text, **kwargs)
```

**Comment by amckenna-pinterest** [comment]
Also update docstring :D

**Comment by balajijegan** [comment]
@amckenna-pinterest  Thanks for comments. Doc string and signature updated. I did not use **kwargs because it might cause confusion. If this changes often, we can consider the approach.

**Comment by balajijegan** [comment]
@arcticfoxnv  Please review when you get a chance. Could you also add @amckenna-pinterest who is another team member the ability to merge to the repo and publish to pypi. 

Thanks
-balaji

**Comment by amckenna-pinterest** [comment]
@arcticfoxnv I'm https://pypi.org/user/amckenna/ thanks!

**Comment by arcticfoxnv** [comment]
Added.

**Pull request merged**
